// Package engine owns the eBPF lifecycle: loading the compiled probes,
// attaching them to their hooks, and turning the ring buffer's raw byte
// records into a channel of model.Event.
package engine

import (
	"context"
	"errors"
	"fmt"
	"os"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"golang.org/x/sys/unix"

	"github.com/thefoulowl/provctl/internal/model"
)

// Engine holds every kernel-side resource: the loaded programs/maps, the
// live attachments, and the ring buffer reader. Call Close to tear
// everything down and detach cleanly.
type Engine struct {
	objs      ProbesObjects
	links     []link.Link
	rd        *ringbuf.Reader
	clock     model.Clock
	closeOnce sync.Once
	closeErr  error
}

// closeReader closes the ring buffer reader exactly once. Both the
// context-cancellation goroutine in Events and Close race to do this.
func (e *Engine) closeReader() error {
	e.closeOnce.Do(func() { e.closeErr = e.rd.Close() })
	return e.closeErr
}

// Open loads the BPF object, attaches every probe, and opens the ring
// buffer. It requires CAP_BPF + CAP_PERFMON (in practice: root) and a
// kernel with BTF exposed at /sys/kernel/btf/vmlinux.
func Open() (*Engine, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("engine: raise memlock rlimit: %w", err)
	}

	var objs ProbesObjects
	if err := LoadProbesObjects(&objs, nil); err != nil {
		var ve *ebpf.VerifierError
		if errors.As(err, &ve) {
			return nil, fmt.Errorf("engine: verifier rejected probes:\n%+v", ve)
		}
		return nil, fmt.Errorf("engine: load probes: %w", err)
	}

	e := &Engine{objs: objs}

	if err := e.selfExclude(); err != nil {
		e.objs.Close()
		return nil, err
	}

	if err := e.attachAll(); err != nil {
		e.Close()
		return nil, err
	}

	rd, err := ringbuf.NewReader(e.objs.Events)
	if err != nil {
		e.Close()
		return nil, fmt.Errorf("engine: open ring buffer: %w", err)
	}
	e.rd = rd

	var mono unix.Timespec
	if err := unix.ClockGettime(unix.CLOCK_MONOTONIC, &mono); err != nil {
		e.Close()
		return nil, fmt.Errorf("engine: read monotonic clock: %w", err)
	}
	e.clock = model.NewClock(uint64(mono.Sec)*1e9+uint64(mono.Nsec), time.Now())

	return e, nil
}

// selfExclude writes provctl's own pid into the self_pid map so probes skip
// events generated by provctl's own file opens, log writes, and DB access —
// otherwise the daemon endlessly traces itself.
func (e *Engine) selfExclude() error {
	key := uint32(0)
	pid := uint32(os.Getpid())
	if err := e.objs.SelfPid.Put(key, pid); err != nil {
		return fmt.Errorf("engine: set self_pid: %w", err)
	}
	return nil
}

func (e *Engine) attachAll() error {
	attach := func(name string, l link.Link, err error) error {
		if err != nil {
			return fmt.Errorf("engine: attach %s: %w", name, err)
		}
		e.links = append(e.links, l)
		return nil
	}

	steps := []struct {
		name string
		open func() (link.Link, error)
	}{
		{"sched_process_fork", func() (link.Link, error) {
			return link.Tracepoint("sched", "sched_process_fork", e.objs.HandleFork, nil)
		}},
		{"sched_process_exec", func() (link.Link, error) {
			return link.Tracepoint("sched", "sched_process_exec", e.objs.HandleExec, nil)
		}},
		{"sched_process_exit", func() (link.Link, error) {
			return link.Tracepoint("sched", "sched_process_exit", e.objs.HandleExit, nil)
		}},
		{"security_file_open", func() (link.Link, error) {
			return link.AttachTracing(link.TracingOptions{Program: e.objs.HandleFileOpen})
		}},
		{"tcp_v4_connect", func() (link.Link, error) {
			return link.AttachTracing(link.TracingOptions{Program: e.objs.HandleTcpV4Connect})
		}},
		{"tcp_v6_connect", func() (link.Link, error) {
			return link.AttachTracing(link.TracingOptions{Program: e.objs.HandleTcpV6Connect})
		}},
	}

	for _, s := range steps {
		l, err := s.open()
		if err := attach(s.name, l, err); err != nil {
			return err
		}
	}
	return nil
}

// Events streams decoded events until ctx is cancelled or Close is called.
// It is meant to be run from a single goroutine.
func (e *Engine) Events(ctx context.Context, out chan<- model.Event) error {
	// Unblock the blocking Read below when the caller cancels. stopped
	// lets this goroutine exit if Events returns for any other reason
	// (a read error), rather than lingering until process teardown.
	stopped := make(chan struct{})
	defer close(stopped)
	go func() {
		select {
		case <-ctx.Done():
			e.closeReader()
		case <-stopped:
		}
	}()

	for {
		rec, err := e.rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) || ctx.Err() != nil {
				return nil
			}
			return fmt.Errorf("engine: read ring buffer: %w", err)
		}

		ev, err := model.Decode(rec.RawSample, e.clock)
		if err != nil {
			continue // malformed record; skip rather than crash the daemon
		}

		select {
		case out <- ev:
		case <-ctx.Done():
			return nil
		}
	}
}

// Close detaches every probe and releases the ring buffer and map fds.
// Safe to call after Events has already returned: the reader is closed at
// most once, so the usual `defer eng.Close()` alongside a cancelled
// context doesn't report a spurious "already closed" error.
func (e *Engine) Close() error {
	var errs []error
	if e.rd != nil {
		if err := e.closeReader(); err != nil {
			errs = append(errs, err)
		}
	}
	for _, l := range e.links {
		if err := l.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if err := e.objs.Close(); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}
