// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package engine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ProbesMapEvents              = "events"
	ProbesMapSelfPid             = "self_pid"
	ProbesProgHandleExec         = "handle_exec"
	ProbesProgHandleExit         = "handle_exit"
	ProbesProgHandleFileOpen     = "handle_file_open"
	ProbesProgHandleFork         = "handle_fork"
	ProbesProgHandleTcpV4Connect = "handle_tcp_v4_connect"
	ProbesProgHandleTcpV6Connect = "handle_tcp_v6_connect"
)

// LoadProbes returns the embedded CollectionSpec for Probes.
func LoadProbes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Probes: %w", err)
	}

	return spec, err
}

// LoadProbesObjects loads Probes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProbesObjects
//	*ProbesPrograms
//	*ProbesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProbesObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProbes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProbesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbesSpecs struct {
	ProbesProgramSpecs
	ProbesMapSpecs
	ProbesVariableSpecs
}

// ProbesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbesProgramSpecs struct {
	HandleExec         *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleExit         *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFileOpen     *ebpf.ProgramSpec `ebpf:"handle_file_open"`
	HandleFork         *ebpf.ProgramSpec `ebpf:"handle_fork"`
	HandleTcpV4Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_connect"`
}

// ProbesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbesMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	SelfPid *ebpf.MapSpec `ebpf:"self_pid"`
}

// ProbesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbesVariableSpecs struct {
}

// ProbesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbesObjects struct {
	ProbesPrograms
	ProbesMaps
	ProbesVariables
}

func (o *ProbesObjects) Close() error {
	return _ProbesClose(
		&o.ProbesPrograms,
		&o.ProbesMaps,
	)
}

// ProbesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbesMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	SelfPid *ebpf.Map `ebpf:"self_pid"`
}

func (m *ProbesMaps) Close() error {
	return _ProbesClose(
		m.Events,
		m.SelfPid,
	)
}

// ProbesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbesVariables struct {
}

// ProbesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbesPrograms struct {
	HandleExec         *ebpf.Program `ebpf:"handle_exec"`
	HandleExit         *ebpf.Program `ebpf:"handle_exit"`
	HandleFileOpen     *ebpf.Program `ebpf:"handle_file_open"`
	HandleFork         *ebpf.Program `ebpf:"handle_fork"`
	HandleTcpV4Connect *ebpf.Program `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect *ebpf.Program `ebpf:"handle_tcp_v6_connect"`
}

func (p *ProbesPrograms) Close() error {
	return _ProbesClose(
		p.HandleExec,
		p.HandleExit,
		p.HandleFileOpen,
		p.HandleFork,
		p.HandleTcpV4Connect,
		p.HandleTcpV6Connect,
	)
}

func _ProbesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probes_x86_bpfel.o
var _ProbesBytes []byte
